<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ7pLkQS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ7pLkQS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ7pLkQS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ7pLkQS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ7pLkQS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q7pLkQS',
    'container.build_id' => 'fc800563',
    'container.build_time' => 1641388713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ7pLkQS');
